# <div style="text-align: center">The Data Scientist’s Toolbox Tutorial - 2</div>

### <div style="text-align: center">CLEAR DATA. MADE MODEL.</div>
<div style="text-align:center">last update: <b>30/12/2018</b></div>


>###### Before starting to read this kernel, It is a good idea review first step: 
1. [The Data Scientist’s Toolbox Tutorial - 1](https://www.kaggle.com/mjbahmani/the-data-scientist-s-toolbox-tutorial-1)
2. <font color="red">You are in the second step</font>
3. [Mathematics and Linear Algebra](https://www.kaggle.com/mjbahmani/linear-algebra-for-data-scientists)
4. [Programming &amp; Analysis Tools](https://www.kaggle.com/mjbahmani/20-ml-algorithms-15-plot-for-beginners)
5. [Big Data](https://www.kaggle.com/mjbahmani/a-data-science-framework-for-quora)
6. [Data visualization](https://www.kaggle.com/mjbahmani/top-5-data-visualization-libraries-tutorial)
7. [Data Cleaning](https://www.kaggle.com/mjbahmani/machine-learning-workflow-for-house-prices)
8. [How to solve a Problem?](https://www.kaggle.com/mjbahmani/the-data-scientist-s-toolbox-tutorial-2)
9. [Machine Learning](https://www.kaggle.com/mjbahmani/a-comprehensive-ml-workflow-with-python)
10. [Deep Learning](https://www.kaggle.com/mjbahmani/top-5-deep-learning-frameworks-tutorial)

---------------------------------------------------------------------
You can Fork and Run this kernel on Github:
> ###### [ GitHub](https://github.com/mjbahmani/10-steps-to-become-a-data-scientist)

-------------------------------------------------------------------------------------------------------------

 **I hope you find this kernel helpful and some <font color="red"><b>UPVOTES</b></font> would be very much appreciated**
 
 -----------

 <a id="top"></a> <br>
## Notebook  Content
1. [Introduction](#1)
    1. [Import](#2)
    1. [Version](#3)
1. [NumPy](#2)
    1. [Creating Arrays](#21)
    1. [How We Can Combining Arrays?](#22)
    1. [Operations](#23)
    1. [How to use Sklearn Data Set? ](#24)
    1. [Loading external data](#25)
    1. [Model Deployment](#26)
    1. [Families of ML algorithms](#27)
    1. [Prepare Features & Targets](#28)
    1. [Accuracy and precision](#29)
    1. [Estimators](#210)
    1. [Predictors](#211)
1. [Pandas](#3)
    1. [DataFrame  ](#31)
    1. [Missing values](#32)
    1. [Merging Dataframes](#33)
    1. [Making Code Pandorable](#34)
    1. [Group by](#35)
    1. [Scales](#36)
1. [Sklearn](#4)
    1. [Algorithms ](#41)
1. [conclusion](#5)
1. [References](#6)

<a id="1"></a> <br>
# 1-Introduction

This Kernel is mostly for **beginners**, and of course, all **professionals** who think they need to review  their  knowledge.
Also, this is  the second version for (  [The Data Scientist’s Toolbox Tutorial - 1](https://www.kaggle.com/mjbahmani/the-data-scientist-s-toolbox-tutorial-1) ) and we will continue with other important packages in this kernel.keep following!
In this section of the tutorial, we introduce two other functional libraries that are required for each specialist.
1. Numpy
1. Pandas

This kernels is based on following perfect tutorails and I want to give them credits:
1. [Coursera-data-science-python](https://www.coursera.org/specializations/data-science-python)
1. [Sklearn](https://scikit-learn.org)
1. [Feature Scaling with scikit-learn](http://benalexkeen.com/feature-scaling-with-scikit-learn/)
1. [https://docs.scipy.org/doc/numpy/user/quickstart.html](https://docs.scipy.org/doc/numpy/user/quickstart.html)
1. [https://pandas.pydata.org/](https://pandas.pydata.org/)
1. [https://www.tutorialspoint.com/numpy](https://www.tutorialspoint.com/numpy)
1. [python-numpy-tutorial](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

<a id="11"></a> <br>
##   1-1 Import

In [1]:
from pandas import get_dummies
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib
import warnings
import scipy
import numpy
import json
import sys
import csv
import os

<a id="12"></a> <br>
## 1-2 Version

In [2]:
print('scipy: {}'.format(scipy.__version__))
print('seaborn: {}'.format(sns.__version__))
print('pandas: {}'.format(pd.__version__))
print('numpy: {}'.format(np.__version__))
print('Python: {}'.format(sys.version))

scipy: 1.4.1
seaborn: 0.10.0
pandas: 1.0.3
numpy: 1.18.1
Python: 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 23:51:54) 
[GCC 7.3.0]


<a id="13"></a> <br>
## 1-3 Setup

A few tiny adjustments for better **code readability**

In [3]:
warnings.filterwarnings('ignore')
%precision 2

'%.2f'

<a id="14"></a> <br>
## 1-4 Import DataSets

In [4]:
hp_train=pd.read_csv('./input/melb_data.csv')

<a id="2"></a> <br>
# 2- NumPy
Numpy is an open source library that you can with it do a lot of math operation. for checking it, you can give a visit in this [page](http://www.numpy.org/)

<img src='https://scipy-lectures.org/_images/numpy_indexing.png' width=400 heght=400>
[**Image Credit**](https://scipy-lectures.org/intro/numpy/array_object.html)

Some of its most important features include:
1. stands for Numerical Python
1. Use for mathematical and logical operations
1. Operations related to linear algebra
1. Numpy is good  for  indexing and slicing

For a fast start you can check this [cheatsheat](https://www.datacamp.com/community/blog/python-numpy-cheat-sheet) too.

In [5]:
import numpy as np

<a id="21"></a> <br>
## 2-1 How can I Create  Arrays?

for Creating an Array using following command:

In [6]:
mylist = [1, 2, 3]
myarray = np.array(mylist)
myarray.shape

(3,)

<img src='http://community.datacamp.com.s3.amazonaws.com/community/production/ckeditor_assets/pictures/332/content_arrays-axes.png' width=500 heght=500>
[**Image Credit**](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

In [7]:
myarray.shape

(3,)

<br>
`resize` changes the shape and size of array in-place.

In [8]:
myarray.resize(3, 3)
myarray

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [9]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [12]:
np.diag(myarray)

array([1, 0, 0])

<br>
Create an array using repeating list (or see `np.tile`)

In [13]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [14]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<a id="22"></a> <br>
## 2-2 How We Can Combining Arrays?
[docs.scipy.org](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html)
###### [Go to top](#top)

In [15]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [16]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [17]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<a id="23"></a> <br>
## 2-3 Operations
for learning numpy operator, this good idea to get a visit in this [page](http://scipy-lectures.org/intro/numpy/operations.html)
<img src='http://scipy-lectures.org/_images/numpy_broadcasting.png'>
[Image Credit](http://scipy-lectures.org/intro/numpy/operations.html)
###### [Go to top](#top)

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [18]:
x=np.array([1, 2, 3])
y=np.array([4, 5, 6])

In [19]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [20]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [21]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [22]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [23]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [24]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>
The shape of array `z` is `(2,3)` before transposing.

In [25]:
z.shape

(2, 3)

<br>
Use `.T` to get the transpose.

In [26]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [27]:
z.T.shape

(3, 2)

<br>
Use `.dtype` to see the data type of the elements in the array.

In [28]:
z.dtype

dtype('int64')

<br>
Use `.astype` to cast to a specific type.

In [29]:
z = z.astype('f')
z.dtype

dtype('float32')

<a id="24"></a> <br>
## 2-4 Math Functions
For learning numpy math function, this good idea to get a visit in this [page](https://www.geeksforgeeks.org/numpy-mathematical-function/)
<img src='http://s8.picofile.com/file/8353147492/numpy_math.png'>
[Image Credit](https://www.geeksforgeeks.org/numpy-mathematical-function/)

###### [Go to top](#top)

Numpy has many built in math functions that can be performed on arrays.

In [30]:
myarray = np.array([-4, -2, 1, 3, 5])

In [31]:
myarray.sum()

3

In [32]:
myarray.max()

5

In [33]:
myarray.min()

-4

In [34]:
myarray.mean()

0.6

In [35]:
myarray.std()

3.2619012860600183

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [36]:
myarray.argmax()

4

In [37]:
myarray.argmin()

0

<a id="25"></a> <br>

## 2-5 Indexing / Slicing
For learning numpy Indexing / Slicing , this good idea to get a visit in this [page](https://www.stechies.com/numpy-indexing-slicing/)
<img src='http://s8.picofile.com/file/8353147750/numpy_math2.png'>
[Image Credit](https://www.stechies.com/numpy-indexing-slicing/)
###### [Go to top](#top)

In [38]:
myarray = np.arange(13)**2
myarray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [39]:
myarray[0], myarray[4], myarray[-1]

(0, 16, 144)

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [40]:
myarray[1:5]

array([ 1,  4,  9, 16])

<br>
Use negatives to count from the back.

In [41]:
myarray[-4:]

array([ 81, 100, 121, 144])

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [42]:
myarray[-5::-2]

array([64, 36, 16,  4,  0])

<br>
Let's look at a multidimensional array.

In [43]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Use bracket notation to slice: `array[row, column]`.

In [44]:
r[2, 2]

14

<br>
And use : to select a range of rows or columns.

In [45]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [46]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [47]:
r[-1, ::2]

array([30, 32, 34])

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [48]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.
###### [Go to top](#top)

In [49]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<a id="26"></a> <br>
## 2-6 Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [50]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [51]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` has also been changed!

In [52]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [53]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [54]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<a id="27"></a> <br>
## 2-7 Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [55]:
test = np.random.randint(0, 10, (4,3))
test

array([[9, 0, 2],
       [0, 9, 0],
       [6, 6, 1],
       [3, 2, 8]])

<br>
Iterate by row:

In [56]:
for row in test:
    print(row)

[9 0 2]
[0 9 0]
[6 6 1]
[3 2 8]


<br>
Iterate by index:

In [57]:
for i in range(len(test)):
    print(test[i])

[9 0 2]
[0 9 0]
[6 6 1]
[3 2 8]


<br>
Iterate by row and index:

In [58]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [9 0 2]
row 1 is [0 9 0]
row 2 is [6 6 1]
row 3 is [3 2 8]


<br>
Use `zip` to iterate over multiple iterables.

In [59]:
test2 = test**2
test2

array([[81,  0,  4],
       [ 0, 81,  0],
       [36, 36,  1],
       [ 9,  4, 64]])

In [60]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[9 0 2] + [81  0  4] = [90  0  6]
[0 9 0] + [ 0 81  0] = [ 0 90  0]
[6 6 1] + [36 36  1] = [42 42  2]
[3 2 8] + [ 9  4 64] = [12  6 72]


<a id="28"></a> <br>
## 2-8 The Series Data Structure
One-dimensional ndarray with axis labels (including time series)
For learning Series Data Structure , this good idea to get a visit in this [page](https://www.kdnuggets.com/2017/01/pandas-cheat-sheet.html)
<img src='https://www.kdnuggets.com/wp-content/uploads/pandas-02.png'>
[Image Credit](https://www.kdnuggets.com/2017/01/pandas-cheat-sheet.html)

In [61]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [62]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [63]:
animals = ['Tiger', 'Bear', None]
pd.Series(animals)

0    Tiger
1     Bear
2     None
dtype: object

In [64]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [65]:
import numpy as np
np.nan == None

False

In [66]:
np.nan == np.nan

False

In [67]:
np.isnan(np.nan)

True

In [68]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [69]:
s.index

Index(['Archery', 'Golf', 'Sumo', 'Taekwondo'], dtype='object')

In [70]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s

India      Tiger
America     Bear
Canada     Moose
dtype: object

In [71]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

Golf      Scotland
Sumo         Japan
Hockey         NaN
dtype: object

<a id="29"></a> <br>
# 2-9 Querying a Series

In [72]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [73]:
s.iloc[3]

'South Korea'

In [74]:
s.loc['Golf']

'Scotland'

In [75]:
s[3]

'South Korea'

In [76]:
s['Golf']

'Scotland'

In [77]:
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)

In [78]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

0    100.0
1    120.0
2    101.0
3      3.0
dtype: float64

In [79]:
total = 0
for item in s:
    total+=item
print(total)

324.0


In [80]:
total = np.sum(s)
print(total)

324.0


In [81]:
#this creates a big series of random numbers
s = pd.Series(np.random.randint(0,1000,10000))
s.head()

0    781
1    594
2    267
3    120
4    594
dtype: int64

In [82]:
len(s)

10000

In [83]:
%%timeit -n 100
summary = 0
for item in s:
    summary+=item

1.08 ms ± 18.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [84]:
%%timeit -n 100
summary = np.sum(s)

75.8 µs ± 4.37 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [85]:
s+=2 #adds two to each item in s using broadcasting
s.head()

0    783
1    596
2    269
3    122
4    596
dtype: int64

In [91]:
for label, value in s.iteritems():
    #s.set_value(label, value+2)
    s[label] = value+2
s.head()

0    785
1    598
2    271
3    124
4    598
dtype: int64

In [92]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,100))
for label, value in s.iteritems():
    s.loc[label]= value+2

6.15 ms ± 66.3 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [93]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,100))
s+=2


296 µs ± 16.9 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [94]:
s = pd.Series([1, 2, 3])
s.loc['Animal'] = 'Bears'
s

0             1
1             2
2             3
Animal    Bears
dtype: object

<a id="210"></a> <br>
## 2-10 Distributions in Numpy
###### [Go to top](#top)

In [95]:
np.random.binomial(1, 0.5)

0

In [96]:
np.random.binomial(1000, 0.5)/1000

0.48

In [97]:
chance_of_tornado = 0.01/100
np.random.binomial(100000, chance_of_tornado)

12

In [98]:
chance_of_tornado = 0.01

tornado_events = np.random.binomial(1, chance_of_tornado, 1000000)
    
two_days_in_a_row = 0
for j in range(1,len(tornado_events)-1):
    if tornado_events[j]==1 and tornado_events[j-1]==1:
        two_days_in_a_row+=1

print('{} tornadoes back to back in {} years'.format(two_days_in_a_row, 1000000/365))

115 tornadoes back to back in 2739.72602739726 years


In [99]:
np.random.uniform(0, 1)

0.91

In [100]:
np.random.normal(0.75)

1.18

In [101]:
distribution = np.random.normal(0.75,size=1000)

np.sqrt(np.sum((np.mean(distribution)-distribution)**2)/len(distribution))

0.9945482919185892

In [102]:
np.std(distribution)

0.9945482919185892

<a id="3"></a> <br>
## 3- Pandas
Pandas is capable of many tasks including  [Based on this [page](https://medium.com/dunder-data/how-to-learn-pandas-108905ab4955)]:

1. Reading/writing many different data formats
1. Selecting subsets of data
1. Calculating across rows and down columns
1. Finding and filling missing data
1. Applying operations to independent groups within the data
1. Reshaping data into different forms
1. Combing multiple datasets together
1. Advanced time-series functionality
1. Visualization through matplotlib and seaborn

###### [Go to top](#top)

In [103]:

purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [104]:
df.loc['Store 2']

Name                  Vinod
Item Purchased    Bird Seed
Cost                      5
Name: Store 2, dtype: object

In [105]:
type(df.loc['Store 2'])

pandas.core.series.Series

In [106]:
df.loc['Store 1']

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5

In [107]:
df.loc['Store 1', 'Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [108]:
df.T

Store 1       Store 1    Store 2
Name               Chris         Kevyn      Vinod
Item Purchased  Dog Food  Kitty Litter  Bird Seed
Cost                22.5           2.5          5

In [109]:
df.T.loc['Cost']

Store 1    22.5
Store 1     2.5
Store 2       5
Name: Cost, dtype: object

In [110]:
df['Cost']

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [111]:
df.loc['Store 1']['Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [112]:
df.loc[:,['Name', 'Cost']]

Name  Cost
Store 1  Chris  22.5
Store 1  Kevyn   2.5
Store 2  Vinod   5.0

In [113]:
df.drop('Store 1')

Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [114]:
df

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [115]:
copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [116]:
copy_df.drop

<bound method DataFrame.drop of           Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0>

In [117]:
del copy_df['Name']
copy_df

Item Purchased  Cost
Store 2      Bird Seed   5.0

In [118]:
df['Location'] = None
df

Name Item Purchased  Cost Location
Store 1  Chris       Dog Food  22.5     None
Store 1  Kevyn   Kitty Litter   2.5     None
Store 2  Vinod      Bird Seed   5.0     None

In [119]:
costs = df['Cost']
costs

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [120]:
costs+=2
costs

Store 1    24.5
Store 1     4.5
Store 2     7.0
Name: Cost, dtype: float64

In [121]:
df

Name Item Purchased  Cost Location
Store 1  Chris       Dog Food  24.5     None
Store 1  Kevyn   Kitty Litter   4.5     None
Store 2  Vinod      Bird Seed   7.0     None

<a id="31"></a> <br>
# 3-1 Dataframe

As a Data Scientist, you'll often find that the data you need is not in a single file. It may be spread across a number of text files, spreadsheets, or databases. You want to be able to import the data of interest as a collection of DataFrames and figure out how to combine them to answer your central questions.
###### [Go to top](#top)

In [127]:
df = pd.read_csv('./input/melb_data.csv')
df.head()

Unnamed: 0      Suburb           Address  Rooms Type      Price Method  \
0           1  Abbotsford      85 Turner St      2    h  1480000.0      S   
1           2  Abbotsford   25 Bloomburg St      2    h  1035000.0      S   
2           4  Abbotsford      5 Charles St      3    h  1465000.0     SP   
3           5  Abbotsford  40 Federation La      3    h   850000.0     PI   
4           6  Abbotsford       55a Park St      4    h  1600000.0     VB   

  SellerG       Date  Distance  ...  Bathroom  Car  Landsize  BuildingArea  \
0  Biggin  3/12/2016       2.5  ...       1.0  1.0     202.0           NaN   
1  Biggin  4/02/2016       2.5  ...       1.0  0.0     156.0          79.0   
2  Biggin  4/03/2017       2.5  ...       2.0  0.0     134.0         150.0   
3  Biggin  4/03/2017       2.5  ...       2.0  1.0      94.0           NaN   
4  Nelson  4/06/2016       2.5  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea  Lattitude Longtitude             Regionname  \
0        NaN        Yarra   -37.7996   144.9984  Northern Metropolitan   
1     1900.0        Yarra   -37.8079   144.9934  Northern Metropolitan   
2     1900.0        Yarra   -37.8093   144.9944  Northern Metropolitan   
3        NaN        Yarra   -37.7969   144.9969  Northern Metropolitan   
4     2014.0        Yarra   -37.8072   144.9941  Northern Metropolitan   

   Propertycount  
0         4019.0  
1         4019.0  
2         4019.0  
3         4019.0  
4         4019.0  

[5 rows x 22 columns]

In [128]:
df.columns

Index(['Unnamed: 0', 'Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method',
       'SellerG', 'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea',
       'Lattitude', 'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [129]:
# Querying a DataFrame

In [130]:
df['Price'] > 10000000

0        False
1        False
2        False
3        False
4        False
         ...  
18391    False
18392    False
18393    False
18394    False
18395    False
Name: Price, Length: 18396, dtype: bool

In [131]:
only_SalePrice = df.where(df['Price'] > 0)
only_SalePrice.head()

Unnamed: 0      Suburb           Address  Rooms Type      Price Method  \
0           1  Abbotsford      85 Turner St      2    h  1480000.0      S   
1           2  Abbotsford   25 Bloomburg St      2    h  1035000.0      S   
2           4  Abbotsford      5 Charles St      3    h  1465000.0     SP   
3           5  Abbotsford  40 Federation La      3    h   850000.0     PI   
4           6  Abbotsford       55a Park St      4    h  1600000.0     VB   

  SellerG       Date  Distance  ...  Bathroom  Car  Landsize  BuildingArea  \
0  Biggin  3/12/2016       2.5  ...       1.0  1.0     202.0           NaN   
1  Biggin  4/02/2016       2.5  ...       1.0  0.0     156.0          79.0   
2  Biggin  4/03/2017       2.5  ...       2.0  0.0     134.0         150.0   
3  Biggin  4/03/2017       2.5  ...       2.0  1.0      94.0           NaN   
4  Nelson  4/06/2016       2.5  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea  Lattitude Longtitude             Regionname  \
0        NaN        Yarra   -37.7996   144.9984  Northern Metropolitan   
1     1900.0        Yarra   -37.8079   144.9934  Northern Metropolitan   
2     1900.0        Yarra   -37.8093   144.9944  Northern Metropolitan   
3        NaN        Yarra   -37.7969   144.9969  Northern Metropolitan   
4     2014.0        Yarra   -37.8072   144.9941  Northern Metropolitan   

   Propertycount  
0         4019.0  
1         4019.0  
2         4019.0  
3         4019.0  
4         4019.0  

[5 rows x 22 columns]

In [132]:
only_SalePrice['Price'].count()

18396

In [133]:
df['Price'].count()

18396

In [134]:
only_SalePrice = only_SalePrice.dropna()
only_SalePrice.head()

Unnamed: 0      Suburb          Address  Rooms Type      Price Method  \
1           2  Abbotsford  25 Bloomburg St      2    h  1035000.0      S   
2           4  Abbotsford     5 Charles St      3    h  1465000.0     SP   
4           6  Abbotsford      55a Park St      4    h  1600000.0     VB   
6          11  Abbotsford     124 Yarra St      3    h  1876000.0      S   
7          14  Abbotsford    98 Charles St      2    h  1636000.0      S   

  SellerG       Date  Distance  ...  Bathroom  Car  Landsize  BuildingArea  \
1  Biggin  4/02/2016       2.5  ...       1.0  0.0     156.0          79.0   
2  Biggin  4/03/2017       2.5  ...       2.0  0.0     134.0         150.0   
4  Nelson  4/06/2016       2.5  ...       1.0  2.0     120.0         142.0   
6  Nelson  7/05/2016       2.5  ...       2.0  0.0     245.0         210.0   
7  Nelson  8/10/2016       2.5  ...       1.0  2.0     256.0         107.0   

   YearBuilt  CouncilArea  Lattitude Longtitude             Regionname  \
1     1900.0        Yarra   -37.8079   144.9934  Northern Metropolitan   
2     1900.0        Yarra   -37.8093   144.9944  Northern Metropolitan   
4     2014.0        Yarra   -37.8072   144.9941  Northern Metropolitan   
6     1910.0        Yarra   -37.8024   144.9993  Northern Metropolitan   
7     1890.0        Yarra   -37.8060   144.9954  Northern Metropolitan   

   Propertycount  
1         4019.0  
2         4019.0  
4         4019.0  
6         4019.0  
7         4019.0  

[5 rows x 22 columns]

In [135]:
only_SalePrice = df[df['Price'] > 0]
only_SalePrice.head()

Unnamed: 0      Suburb           Address  Rooms Type      Price Method  \
0           1  Abbotsford      85 Turner St      2    h  1480000.0      S   
1           2  Abbotsford   25 Bloomburg St      2    h  1035000.0      S   
2           4  Abbotsford      5 Charles St      3    h  1465000.0     SP   
3           5  Abbotsford  40 Federation La      3    h   850000.0     PI   
4           6  Abbotsford       55a Park St      4    h  1600000.0     VB   

  SellerG       Date  Distance  ...  Bathroom  Car  Landsize  BuildingArea  \
0  Biggin  3/12/2016       2.5  ...       1.0  1.0     202.0           NaN   
1  Biggin  4/02/2016       2.5  ...       1.0  0.0     156.0          79.0   
2  Biggin  4/03/2017       2.5  ...       2.0  0.0     134.0         150.0   
3  Biggin  4/03/2017       2.5  ...       2.0  1.0      94.0           NaN   
4  Nelson  4/06/2016       2.5  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea  Lattitude Longtitude             Regionname  \
0        NaN        Yarra   -37.7996   144.9984  Northern Metropolitan   
1     1900.0        Yarra   -37.8079   144.9934  Northern Metropolitan   
2     1900.0        Yarra   -37.8093   144.9944  Northern Metropolitan   
3        NaN        Yarra   -37.7969   144.9969  Northern Metropolitan   
4     2014.0        Yarra   -37.8072   144.9941  Northern Metropolitan   

   Propertycount  
0         4019.0  
1         4019.0  
2         4019.0  
3         4019.0  
4         4019.0  

[5 rows x 22 columns]

In [136]:
len(df[(df['Price'] > 0) | (df['Price'] > 0)])

18396

In [137]:
df[(df['Price'] > 0) & (df['Price'] == 0)]

Empty DataFrame
Columns: [Unnamed: 0, Suburb, Address, Rooms, Type, Price, Method, SellerG, Date, Distance, Postcode, Bedroom2, Bathroom, Car, Landsize, BuildingArea, YearBuilt, CouncilArea, Lattitude, Longtitude, Regionname, Propertycount]
Index: []

[0 rows x 22 columns]

<a id="311"></a> <br>
## 3-1-1 Dataframes

In [138]:
df.head()

Unnamed: 0      Suburb           Address  Rooms Type      Price Method  \
0           1  Abbotsford      85 Turner St      2    h  1480000.0      S   
1           2  Abbotsford   25 Bloomburg St      2    h  1035000.0      S   
2           4  Abbotsford      5 Charles St      3    h  1465000.0     SP   
3           5  Abbotsford  40 Federation La      3    h   850000.0     PI   
4           6  Abbotsford       55a Park St      4    h  1600000.0     VB   

  SellerG       Date  Distance  ...  Bathroom  Car  Landsize  BuildingArea  \
0  Biggin  3/12/2016       2.5  ...       1.0  1.0     202.0           NaN   
1  Biggin  4/02/2016       2.5  ...       1.0  0.0     156.0          79.0   
2  Biggin  4/03/2017       2.5  ...       2.0  0.0     134.0         150.0   
3  Biggin  4/03/2017       2.5  ...       2.0  1.0      94.0           NaN   
4  Nelson  4/06/2016       2.5  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea  Lattitude Longtitude             Regionname  \
0        NaN        Yarra   -37.7996   144.9984  Northern Metropolitan   
1     1900.0        Yarra   -37.8079   144.9934  Northern Metropolitan   
2     1900.0        Yarra   -37.8093   144.9944  Northern Metropolitan   
3        NaN        Yarra   -37.7969   144.9969  Northern Metropolitan   
4     2014.0        Yarra   -37.8072   144.9941  Northern Metropolitan   

   Propertycount  
0         4019.0  
1         4019.0  
2         4019.0  
3         4019.0  
4         4019.0  

[5 rows x 22 columns]

In [139]:
df['SalePrice'] = df.index
df = df.set_index('SalePrice')
df.head()

Unnamed: 0      Suburb           Address  Rooms Type      Price  \
SalePrice                                                                    
0                   1  Abbotsford      85 Turner St      2    h  1480000.0   
1                   2  Abbotsford   25 Bloomburg St      2    h  1035000.0   
2                   4  Abbotsford      5 Charles St      3    h  1465000.0   
3                   5  Abbotsford  40 Federation La      3    h   850000.0   
4                   6  Abbotsford       55a Park St      4    h  1600000.0   

          Method SellerG       Date  Distance  ...  Bathroom  Car  Landsize  \
SalePrice                                      ...                            
0              S  Biggin  3/12/2016       2.5  ...       1.0  1.0     202.0   
1              S  Biggin  4/02/2016       2.5  ...       1.0  0.0     156.0   
2             SP  Biggin  4/03/2017       2.5  ...       2.0  0.0     134.0   
3             PI  Biggin  4/03/2017       2.5  ...       2.0  1.0      94.0   
4             VB  Nelson  4/06/2016       2.5  ...       1.0  2.0     120.0   

           BuildingArea  YearBuilt  CouncilArea  Lattitude Longtitude  \
SalePrice                                                               
0                   NaN        NaN        Yarra   -37.7996   144.9984   
1                  79.0     1900.0        Yarra   -37.8079   144.9934   
2                 150.0     1900.0        Yarra   -37.8093   144.9944   
3                   NaN        NaN        Yarra   -37.7969   144.9969   
4                 142.0     2014.0        Yarra   -37.8072   144.9941   

                      Regionname  Propertycount  
SalePrice                                        
0          Northern Metropolitan         4019.0  
1          Northern Metropolitan         4019.0  
2          Northern Metropolitan         4019.0  
3          Northern Metropolitan         4019.0  
4          Northern Metropolitan         4019.0  

[5 rows x 22 columns]

In [140]:

df = df.reset_index()
df.head()

SalePrice  Unnamed: 0      Suburb           Address  Rooms Type      Price  \
0          0           1  Abbotsford      85 Turner St      2    h  1480000.0   
1          1           2  Abbotsford   25 Bloomburg St      2    h  1035000.0   
2          2           4  Abbotsford      5 Charles St      3    h  1465000.0   
3          3           5  Abbotsford  40 Federation La      3    h   850000.0   
4          4           6  Abbotsford       55a Park St      4    h  1600000.0   

  Method SellerG       Date  ...  Bathroom  Car  Landsize  BuildingArea  \
0      S  Biggin  3/12/2016  ...       1.0  1.0     202.0           NaN   
1      S  Biggin  4/02/2016  ...       1.0  0.0     156.0          79.0   
2     SP  Biggin  4/03/2017  ...       2.0  0.0     134.0         150.0   
3     PI  Biggin  4/03/2017  ...       2.0  1.0      94.0           NaN   
4     VB  Nelson  4/06/2016  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea  Lattitude  Longtitude             Regionname  \
0        NaN        Yarra   -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra   -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra   -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra   -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra   -37.8072    144.9941  Northern Metropolitan   

   Propertycount  
0         4019.0  
1         4019.0  
2         4019.0  
3         4019.0  
4         4019.0  

[5 rows x 23 columns]

<a id="32"></a> <br>
# 3-2 Missing values


In [143]:
df = pd.read_csv('./input/melb_data.csv')

In [144]:
df.fillna

<bound method DataFrame.fillna of        Unnamed: 0        Suburb           Address  Rooms Type      Price  \
0               1    Abbotsford      85 Turner St      2    h  1480000.0   
1               2    Abbotsford   25 Bloomburg St      2    h  1035000.0   
2               4    Abbotsford      5 Charles St      3    h  1465000.0   
3               5    Abbotsford  40 Federation La      3    h   850000.0   
4               6    Abbotsford       55a Park St      4    h  1600000.0   
...           ...           ...               ...    ...  ...        ...   
18391       23540  Williamstown   8/2 Thompson St      2    t   622500.0   
18392       23541  Williamstown      96 Verdon St      4    h  2500000.0   
18393       23544     Yallambie      17 Amaroo Wy      4    h  1100000.0   
18394       23545    Yarraville        6 Agnes St      4    h  1285000.0   
18395       23546    Yarraville     33 Freeman St      4    h  1050000.0   

      Method     SellerG        Date  Distance  ...  

In [145]:
df = df.fillna(method='ffill')
df.head()

Unnamed: 0      Suburb           Address  Rooms Type      Price Method  \
0           1  Abbotsford      85 Turner St      2    h  1480000.0      S   
1           2  Abbotsford   25 Bloomburg St      2    h  1035000.0      S   
2           4  Abbotsford      5 Charles St      3    h  1465000.0     SP   
3           5  Abbotsford  40 Federation La      3    h   850000.0     PI   
4           6  Abbotsford       55a Park St      4    h  1600000.0     VB   

  SellerG       Date  Distance  ...  Bathroom  Car  Landsize  BuildingArea  \
0  Biggin  3/12/2016       2.5  ...       1.0  1.0     202.0           NaN   
1  Biggin  4/02/2016       2.5  ...       1.0  0.0     156.0          79.0   
2  Biggin  4/03/2017       2.5  ...       2.0  0.0     134.0         150.0   
3  Biggin  4/03/2017       2.5  ...       2.0  1.0      94.0         150.0   
4  Nelson  4/06/2016       2.5  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea  Lattitude Longtitude             Regionname  \
0        NaN        Yarra   -37.7996   144.9984  Northern Metropolitan   
1     1900.0        Yarra   -37.8079   144.9934  Northern Metropolitan   
2     1900.0        Yarra   -37.8093   144.9944  Northern Metropolitan   
3     1900.0        Yarra   -37.7969   144.9969  Northern Metropolitan   
4     2014.0        Yarra   -37.8072   144.9941  Northern Metropolitan   

   Propertycount  
0         4019.0  
1         4019.0  
2         4019.0  
3         4019.0  
4         4019.0  

[5 rows x 22 columns]

<a id="33"></a> <br>
# 3-3 Merging Dataframes
For learning Merging Dataframes , this is a good idea to give a visit in this [page](https://www.ryanbaumann.com/blog/2016/4/30/python-pandas-tosql-only-insert-new-rows)
<img src='https://static1.squarespace.com/static/54bb1957e4b04c160a32f928/t/5724fd0bf699bb5ad6432150/1462041871236/?format=750w'>
[Image Credit](https://www.ryanbaumann.com/blog/2016/4/30/python-pandas-tosql-only-insert-new-rows)


In [146]:
df = pd.DataFrame([{'Name': 'MJ', 'Item Purchased': 'Sponge', 'Cost': 22.50},
                   {'Name': 'Kevyn', 'Item Purchased': 'Kitty Litter', 'Cost': 2.50},
                   {'Name': 'Filip', 'Item Purchased': 'Spoon', 'Cost': 5.00}],
                  index=['Store 1', 'Store 1', 'Store 2'])
df

Name Item Purchased  Cost
Store 1     MJ         Sponge  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Filip          Spoon   5.0

In [147]:
df['Date'] = ['December 1', 'January 1', 'mid-May']
df

Name Item Purchased  Cost        Date
Store 1     MJ         Sponge  22.5  December 1
Store 1  Kevyn   Kitty Litter   2.5   January 1
Store 2  Filip          Spoon   5.0     mid-May

In [148]:
df['Delivered'] = True
df

Name Item Purchased  Cost        Date  Delivered
Store 1     MJ         Sponge  22.5  December 1       True
Store 1  Kevyn   Kitty Litter   2.5   January 1       True
Store 2  Filip          Spoon   5.0     mid-May       True

In [149]:
df['Feedback'] = ['Positive', None, 'Negative']
df

Name Item Purchased  Cost        Date  Delivered  Feedback
Store 1     MJ         Sponge  22.5  December 1       True  Positive
Store 1  Kevyn   Kitty Litter   2.5   January 1       True      None
Store 2  Filip          Spoon   5.0     mid-May       True  Negative

In [150]:
adf = df.reset_index()
adf['Date'] = pd.Series({0: 'December 1', 2: 'mid-May'})
adf

index   Name Item Purchased  Cost        Date  Delivered  Feedback
0  Store 1     MJ         Sponge  22.5  December 1       True  Positive
1  Store 1  Kevyn   Kitty Litter   2.5         NaN       True      None
2  Store 2  Filip          Spoon   5.0     mid-May       True  Negative

<a id="34"></a> <br>
# 3-4 Making Code Pandorable
based on this amazing **[Article](https://www.datacamp.com/community/tutorials/pandas-idiomatic)**
1. Indexing with the help of **loc** and **iloc**, and a short introduction to querying your DataFrame with query();
1. Method Chaining, with the help of the pipe() function as an alternative to nested functions;
1. Memory Optimization, which you can achieve through setting data types;
1. groupby operation, in the naive and Pandas way; and
1. Visualization of your DataFrames with Matplotlib and Seaborn.

In [153]:
df = pd.read_csv('./input/melb_data.csv')

In [154]:
df.head()

Unnamed: 0      Suburb           Address  Rooms Type      Price Method  \
0           1  Abbotsford      85 Turner St      2    h  1480000.0      S   
1           2  Abbotsford   25 Bloomburg St      2    h  1035000.0      S   
2           4  Abbotsford      5 Charles St      3    h  1465000.0     SP   
3           5  Abbotsford  40 Federation La      3    h   850000.0     PI   
4           6  Abbotsford       55a Park St      4    h  1600000.0     VB   

  SellerG       Date  Distance  ...  Bathroom  Car  Landsize  BuildingArea  \
0  Biggin  3/12/2016       2.5  ...       1.0  1.0     202.0           NaN   
1  Biggin  4/02/2016       2.5  ...       1.0  0.0     156.0          79.0   
2  Biggin  4/03/2017       2.5  ...       2.0  0.0     134.0         150.0   
3  Biggin  4/03/2017       2.5  ...       2.0  1.0      94.0           NaN   
4  Nelson  4/06/2016       2.5  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea  Lattitude Longtitude             Regionname  \
0        NaN        Yarra   -37.7996   144.9984  Northern Metropolitan   
1     1900.0        Yarra   -37.8079   144.9934  Northern Metropolitan   
2     1900.0        Yarra   -37.8093   144.9944  Northern Metropolitan   
3        NaN        Yarra   -37.7969   144.9969  Northern Metropolitan   
4     2014.0        Yarra   -37.8072   144.9941  Northern Metropolitan   

   Propertycount  
0         4019.0  
1         4019.0  
2         4019.0  
3         4019.0  
4         4019.0  

[5 rows x 22 columns]

<a id="35"></a> <br>
## 3-5 Group by

In [155]:
df = df[df['Price']>500000]
df

Unnamed: 0        Suburb           Address  Rooms Type      Price  \
0               1    Abbotsford      85 Turner St      2    h  1480000.0   
1               2    Abbotsford   25 Bloomburg St      2    h  1035000.0   
2               4    Abbotsford      5 Charles St      3    h  1465000.0   
3               5    Abbotsford  40 Federation La      3    h   850000.0   
4               6    Abbotsford       55a Park St      4    h  1600000.0   
...           ...           ...               ...    ...  ...        ...   
18391       23540  Williamstown   8/2 Thompson St      2    t   622500.0   
18392       23541  Williamstown      96 Verdon St      4    h  2500000.0   
18393       23544     Yallambie      17 Amaroo Wy      4    h  1100000.0   
18394       23545    Yarraville        6 Agnes St      4    h  1285000.0   
18395       23546    Yarraville     33 Freeman St      4    h  1050000.0   

      Method     SellerG        Date  Distance  ...  Bathroom  Car  Landsize  \
0          S      Biggin   3/12/2016       2.5  ...       1.0  1.0     202.0   
1          S      Biggin   4/02/2016       2.5  ...       1.0  0.0     156.0   
2         SP      Biggin   4/03/2017       2.5  ...       2.0  0.0     134.0   
3         PI      Biggin   4/03/2017       2.5  ...       2.0  1.0      94.0   
4         VB      Nelson   4/06/2016       2.5  ...       1.0  2.0     120.0   
...      ...         ...         ...       ...  ...       ...  ...       ...   
18391     SP        Greg  26/08/2017       6.8  ...       2.0  1.0       NaN   
18392     PI     Sweeney  26/08/2017       6.8  ...       1.0  5.0     866.0   
18393      S  Buckingham  26/08/2017      12.7  ...       3.0  2.0       NaN   
18394     SP     Village  26/08/2017       6.3  ...       1.0  1.0     362.0   
18395     VB     Village  26/08/2017       6.3  ...       2.0  2.0       NaN   

       BuildingArea  YearBuilt  CouncilArea  Lattitude Longtitude  \
0               NaN        NaN        Yarra  -37.79960  144.99840   
1              79.0     1900.0        Yarra  -37.80790  144.99340   
2             150.0     1900.0        Yarra  -37.80930  144.99440   
3               NaN        NaN        Yarra  -37.79690  144.99690   
4             142.0     2014.0        Yarra  -37.80720  144.99410   
...             ...        ...          ...        ...        ...   
18391          89.0     2010.0          NaN  -37.86393  144.90484   
18392         157.0     1920.0          NaN  -37.85908  144.89299   
18393           NaN        NaN          NaN  -37.72006  145.10547   
18394         112.0     1920.0          NaN  -37.81188  144.88449   
18395         139.0     1950.0          NaN  -37.81829  144.87404   

                  Regionname  Propertycount  
0      Northern Metropolitan         4019.0  
1      Northern Metropolitan         4019.0  
2      Northern Metropolitan         4019.0  
3      Northern Metropolitan         4019.0  
4      Northern Metropolitan         4019.0  
...                      ...            ...  
18391   Western Metropolitan         6380.0  
18392   Western Metropolitan         6380.0  
18393  Northern Metropolitan         1369.0  
18394   Western Metropolitan         6543.0  
18395   Western Metropolitan         6543.0  

[16141 rows x 22 columns]

<a id="36"></a> <br>
## 3-6 Scales


In [156]:
df = pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'],
                  index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 'ok', 'ok', 'ok', 'poor', 'poor'])
df.rename(columns={0: 'Grades'}, inplace=True)
df

Grades
excellent     A+
excellent      A
excellent     A-
good          B+
good           B
good          B-
ok            C+
ok             C
ok            C-
poor          D+
poor           D

In [157]:
df['Grades'].astype('category').head()

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
Name: Grades, dtype: category
Categories (11, object): [A, A+, A-, B, ..., C+, C-, D, D+]

In [164]:
from pandas.api.types import CategoricalDtype

grades = df['Grades'].astype('category',
                            CategoricalDtype(categories=['D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+']))
grades.head()

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
Name: Grades, dtype: category
Categories (11, object): [A, A+, A-, B, ..., C+, C-, D, D+]

In [167]:
#grades > 'C'

<a id="361"></a> <br>
## 3-6-1 Select

To select rows whose column value equals a scalar, some_value, use ==:

In [168]:
df.loc[df['Grades'] == 'A+']


Grades
excellent     A+

To select rows whose column value is in an iterable, some_values, use **isin**:

In [169]:
df_test = pd.DataFrame({'A': [1, 2, 3], 'B': [1, 4, 7]})
df_test.isin({'A': [1, 3], 'B': [4, 7, 12]})

A      B
0   True  False
1  False   True
2   True   True

Combine multiple conditions with &:

In [170]:
df.loc[(df['Grades'] == 'A+') & (df['Grades'] == 'D')]


Empty DataFrame
Columns: [Grades]
Index: []

To select rows whose column value does not equal some_value, use !=:


In [171]:

df.loc[df['Grades'] != 'B+']


Grades
excellent     A+
excellent      A
excellent     A-
good           B
good          B-
ok            C+
ok             C
ok            C-
poor          D+
poor           D

isin returns a boolean Series, so to select rows whose value is not in some_values, negate the boolean Series using ~:


In [172]:
df_test = pd.DataFrame({'A': [1, 2, 3], 'B': [1, 4, 7]})

In [173]:
df_test.loc[~df_test['A'].isin({'A': [1, 3], 'B': [4, 7, 12]})]

A  B
0  1  1
1  2  4
2  3  7

<a id="37"></a> <br>
## 3-7 Date Functionality
###### [Go to top](#top)

<a id="371"></a> <br>
### 3-7-1 Timestamp

In [174]:
pd.Timestamp('9/1/2016 10:05AM')

Timestamp('2016-09-01 10:05:00')

<a id="372"></a> <br>
### 3-7-2 Period

In [175]:
pd.Period('1/2016')

Period('2016-01', 'M')

In [176]:
pd.Period('3/5/2016')

Period('2016-03-05', 'D')

<a id="373"></a> <br>
### 3-7-3 DatetimeIndex

In [177]:
t1 = pd.Series(list('abc'), [pd.Timestamp('2016-09-01'), pd.Timestamp('2016-09-02'), pd.Timestamp('2016-09-03')])
t1

2016-09-01    a
2016-09-02    b
2016-09-03    c
dtype: object

In [178]:
type(t1.index)

pandas.core.indexes.datetimes.DatetimeIndex

<a id="374"></a> <br>
### 3-7-4 PeriodIndex

In [179]:
t2 = pd.Series(list('def'), [pd.Period('2016-09'), pd.Period('2016-10'), pd.Period('2016-11')])
t2

2016-09    d
2016-10    e
2016-11    f
Freq: M, dtype: object

In [180]:
type(t2.index)

pandas.core.indexes.period.PeriodIndex

<a id="38"></a> <br>
## 3-8 Converting to Datetime

In [181]:
d1 = ['2 June 2013', 'Aug 29, 2014', '2015-06-26', '7/12/16']
ts3 = pd.DataFrame(np.random.randint(10, 100, (4,2)), index=d1, columns=list('ab'))
ts3

a   b
2 June 2013   93  30
Aug 29, 2014  23  20
2015-06-26    51  58
7/12/16       82  43

In [182]:
ts3.index = pd.to_datetime(ts3.index)
ts3

a   b
2013-06-02  93  30
2014-08-29  23  20
2015-06-26  51  58
2016-07-12  82  43

In [183]:
pd.to_datetime('4.7.12', dayfirst=True)

Timestamp('2012-07-04 00:00:00')

In [184]:
pd.Timestamp('9/3/2016')-pd.Timestamp('9/1/2016')

Timedelta('2 days 00:00:00')

<a id="381"></a> <br>
### 3-8-1 Timedeltas

In [185]:
pd.Timestamp('9/3/2016')-pd.Timestamp('9/1/2016')

Timedelta('2 days 00:00:00')

In [186]:
pd.Timestamp('9/2/2016 8:10AM') + pd.Timedelta('12D 3H')

Timestamp('2016-09-14 11:10:00')

<a id="382"></a> <br>
### 3-8-2 Working with Dates in a Dataframe


In [187]:
dates = pd.date_range('10-01-2016', periods=9, freq='2W-SUN')
dates

DatetimeIndex(['2016-10-02', '2016-10-16', '2016-10-30', '2016-11-13',
               '2016-11-27', '2016-12-11', '2016-12-25', '2017-01-08',
               '2017-01-22'],
              dtype='datetime64[ns]', freq='2W-SUN')

In [188]:
df.index.ravel

<bound method Index.ravel of Index(['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 'ok',
       'ok', 'ok', 'poor', 'poor'],
      dtype='object')>

<a id="4"></a> <br>
# 4- Sklearn 
[sklearn has following feature](https://scikit-learn.org/stable/):
1. Simple and efficient tools for data mining and data analysis
1. Accessible to everybody, and reusable in various contexts
1. Built on NumPy, SciPy, and matplotlib
1. Open source, commercially usable - BSD license

<a id="41"></a> <br>
## 4-1 Algorithms

**Supervised learning**:

1. Linear models (Ridge, Lasso, Elastic Net, ...)
1. Support Vector Machines
1. Tree-based methods (Random Forests, Bagging, GBRT, ...)
1. Nearest neighbors 
1. Neural networks (basics)
1. Gaussian Processes
1. Feature selection

**Unsupervised learning**:

1. Clustering (KMeans, Ward, ...)
1. Matrix decomposition (PCA, ICA, ...)
1. Density estimation
1. Outlier detection

__Model selection and evaluation:__

1. Cross-validation
1. Grid-search
1. Lots of metrics

_... and many more!_ (See our [Reference](http://scikit-learn.org/dev/modules/classes.html))

For learning this section please give a visit on [this kernel](https://www.kaggle.com/mjbahmani/20-ml-algorithms-15-plot-for-beginners)

<a id="7"></a> <br>
# 7- conclusion
After the first version of this kernel, in the second edition, we introduced Numpy & Pandas. in addition, we examined each one in detail. This kernel is finished due to the large size and you can follow the discussion in the my other kernel.

>###### you may  be interested have a look at it: [**10-steps-to-become-a-data-scientist**](https://github.com/mjbahmani/10-steps-to-become-a-data-scientist)


---------------------------------------------------------------------
you can Fork and Run this kernel on Github:
> ###### [ GitHub](https://github.com/mjbahmani/10-steps-to-become-a-data-scientist)

-------------------------------------------------------------------------------------------------------------

 **I hope you find this kernel helpful and some <font color="red"><b>UPVOTES</b></font> would be very much appreciated**
 
 -----------

<a id="8"></a> <br>
# 8- References & Credits
1. [Coursera](https://www.coursera.org/specializations/data-science-python)
1. [Sklearn](https://scikit-learn.org)
1. [Feature Scaling with scikit-learn](http://benalexkeen.com/feature-scaling-with-scikit-learn/)
1. [https://docs.scipy.org/doc/numpy/user/quickstart.html](https://docs.scipy.org/doc/numpy/user/quickstart.html)
1. [https://pandas.pydata.org/](https://pandas.pydata.org/)
1. [https://www.stechies.com/numpy-indexing-slicing/](https://www.stechies.com/numpy-indexing-slicing/)
1. [python_pandas_dataframe](https://www.tutorialspoint.com/python_pandas/python_pandas_dataframe.htm)
###### [Go to top](#top)

**you may be interested have a look at it: [Course Home Page](https://www.kaggle.com/mjbahmani/10-steps-to-become-a-data-scientist)**